on:
  schedule:
    - cron: 0 10 * * 1-5 # Every monday to friday at 10:00
  workflow_dispatch:

name: Check for broken external links
jobs:
  check-external-links:
    name: Check external links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Install npm packages
        run: yarn --ignore-optional
      - name: Run 'broken-link-checker'
        run: yarn test:links:external
